# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [14]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
import random
a = np.linspace(0,1000000,1000000) * 2 
%time

b = random.sample(range(1000000),1000000) * 2 
%time

Wall time: 0 ns
Wall time: 0 ns


### Exercício 2

In [21]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
a = np.random.rand(10)
for i in range(4):
    a[4+i] = 0
a

array([0.23091945, 0.09626708, 0.59418471, 0.87345802, 0.        ,
       0.        , 0.        , 0.        , 0.666293  , 0.86530102])

### Exercício 3

In [44]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
a = np.random.rand (2,2,2)
a[:,0,0]
a[:,1.1]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### Exercício 4

In [36]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz = np.random.rand (4,4)
matriz[]

array([[0.62030965, 0.90249598, 0.95182968, 0.29365972],
       [0.25864595, 0.10191922, 0.58990246, 0.45323498],
       [0.4680879 , 0.20153366, 0.6932284 , 0.84085755],
       [0.0279514 , 0.85675425, 0.25388599, 0.85137879]])

In [55]:
matriz[0:2,:]
matriz[:,1:3]

array([[0.62030965, 0.90249598, 0.95182968, 0.29365972],
       [0.25864595, 0.10191922, 0.58990246, 0.45323498]])

### Exercício 5

In [56]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
a = np.transpose(arr)
a

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [62]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for i in range(5):
    if cond[i] == True:
        print(xarr[i])
    else:
        print(yarr[i])


1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [65]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

a = np.arange(10)
np.save(exercicio,a)

#pra carregar

b = np.load(exercicio)
b

NameError: name 'exercicio7' is not defined

### Exercício 8

In [67]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
pd.unique(obj)

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [76]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp.text

'[{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/27009","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/27009/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/27009/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/27009/events","html_url":"https://github.com/pandas-dev/pandas/pull/27009","id":459569490,"node_id":"MDExOlB1bGxSZXF1ZXN0MjkwODg1MDYw","number":27009,"title":"WIP/PLT: Cleaner plotting backend API, and unify Series and DataFrame accessors","user":{"login":"datapythonista","id":10058240,"node_id":"MDQ6VXNlcjEwMDU4MjQw","avatar_url":"https://avatars2.githubusercontent.com/u/10058240?v=4","gravatar_id":"","url":"https://api.github.com/users/datapythonista","html_url":"https://github.com/datapythonista","followers_url":"https://api.github.com/users/datapythonista/followers","following_url":"https://api.github.com/use

### Exercício 10
import os
os.remove("meubanco.db") if os.path.exists("meubanco.db") else None

In [99]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
con = sqlite3.connect('meubanco.db')
cur = con.cursor()


In [100]:
sql_create = 'create table leitura '\
'(id integer primary key, '\
'livros varchar(100), '\
'paginas integer, '\
'categoria varchar(140))'

In [101]:
cur.execute(sql_create)

In [107]:
sql_insert = 'insert into leitura values (?, ?, ?, ?)'
# Dados
recset = [(1000, 'Livro A', 500, 'Romance'),
          (1001, 'Livro B', 767, 'Tech'),
          (1002, 'Livro C', 32,  'Acao')]
# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)

In [108]:
sql_select = 'select * from leitura'
cur.execute(sql_select)
dados = cur.fetchall()

In [109]:
for linha in dados:
    print ('Livro Id: %d, Livro: %s, Pagina: %d Categoria: %s \n' % linha)

    

Livro Id: 1000, Livro: Livro A, Pagina: 500 Categoria: Romance 

Livro Id: 1001, Livro: Livro B, Pagina: 767 Categoria: TRech 

Livro Id: 1002, Livro: Livro C, Pagina: 32 Categoria: Acao 



In [115]:
import pandas as pd
df = pd.DataFrame(dados)
df

0        1    2        3
0  1000  Livro A  500  Romance
1  1001  Livro B  767    TRech
2  1002  Livro C   32     Acao

In [116]:
con.close()

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>